version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elk-net
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  logstash:
    image: logstash:8.11.3
    container_name: logstash
    volumes:
      - ./logstash/config.d:/config/conf.d
      - ./logstash/pipeline:/pipeline
    networks:
      - elk-net
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m

  kibana:
    image: kibana:8.11.3
    container_name: kibana
    networks:
      - elk-net
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.11.3
    container_name: apm-server
    volumes:
      - apm-data:/apm-server/data
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - elk-net
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
    environment:
      - SERVER_JAVA_OPTS="-Xms512m -Xmx512m"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=your-elastic-password2  # Replace with your actual password

networks:
  elk-net:
    driver: bridge

volumes:
  es-data:
  apm-data:
